stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cmake -S . -B /shared/build -G Ninja -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
    - cmake --build /shared/build
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - ctest -j6 -T test --output-on-failure --test-dir /shared/build
    - echo "Tests complete."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - cpack -B /shared/release --config /shared/build/CPackConfig.cmake
    - rm -r /shared/release/_CPack_Packages/
    - echo "Application successfully deployed."
