concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner-1"
  url = "http://192.168.1.100/"
  id = 21
  token = "xAmjz-xgvKXcCKBcgSsr"
  token_obtained_at = 2024-06-13T06:57:01Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "dxloc/alpine-cmake:0.1.0"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/tmp/gitlab-runner:/shared:rw"]
    shm_size = 0
    network_mtu = 0
